### ISSUE TITLE
Keine Kommunikation mit eNet-Server Version 2.3.0

### ISSUE THREAD

**Issue by FranzKillig** [SebastianSchultz/ioBroker.enet#29]
Hallo,

nachdem ich mit Basti zusammen schon einige Tage vergeblich versuche den eNet-Adapter (Alpha-Version) zum laufen zu bringen nachfolgende Informationen für Hilfe bei der Fehlerbehebung

eNetServer-Software :  2.3.0 (46735)
ioBroker 4.1.11 auf Raspberry PI 4 mit raspios vom 02.12.2020
Node.js v12.20.1
enet-Server und Raspi sind per LAN im Netz.

Verwendeter Adapter [iobroker.enet.zip](https://github.com/SebastianSchultz/ioBroker.enet/files/5781154/iobroker.enet.zip)

Nachfolgenden Log ergibt sich nach Start der Instanz:

host.raspberrypi | 2021-01-07 11:00:34.922 | info | Restart adapter system.adapter.enet.0 because   enabled
-- | -- | -- | --
host.raspberrypi | 2021-01-07 11:00:34.921 | info | instance system.adapter.enet.0 terminated with   code 0 (NO_ERROR)
enet.0 | 2021-01-07 11:00:34.392 | info | (4482) Terminated (NO_ERROR): Without reason
enet.0 | 2021-01-07 11:00:34.390 | info | (4482) terminating
enet.0 | 2021-01-07   11:00:34.386 | debug | (4482) eNet Server   Logout Request Body IN: {"jsonrpc":"2.0",   "method":"setClientRole",   "params":{"clientRole":"CR_IBN"},   "id":"1"}
enet.0 | 2021-01-07   11:00:34.376 | debug | (4482) eNet Server   Logout Start
enet.0 | 2021-01-07 11:00:34.374 | error | at Socket.Readable.push   (_stream_readable.js:213:10)
enet.0 | 2021-01-07 11:00:34.374 | error | at readableAddChunk (_stream_readable.js:272:9)
enet.0 | 2021-01-07 11:00:34.374 | error | at addChunk (_stream_readable.js:297:12)
enet.0 | 2021-01-07 11:00:34.374 | error | at Socket.emit (events.js:314:20)
enet.0 | 2021-01-07 11:00:34.374 | error | at Socket.socketOnData (_http_client.js:474:22)
enet.0 | 2021-01-07 11:00:34.374 | error | at HTTPParser.parserOnHeadersComplete   (_http_common.js:122:17)
enet.0 | 2021-01-07 11:00:34.374 | error | at HTTPParser.parserOnIncomingClient [as   onIncoming] (_http_client.js:601:27)
enet.0 | 2021-01-07 11:00:34.374 | error | at ClientRequest.emit (events.js:314:20)
enet.0 | 2021-01-07 11:00:34.374 | error | at Object.onceWrapper (events.js:421:26)
enet.0 | 2021-01-07 11:00:34.374 | error | at ClientRequest.<anonymous>   (/opt/iobroker/node_modules/iobroker.enet/main.js:282:62)
enet.0 | 2021-01-07 11:00:34.374 | error | (4482) TypeError: Cannot read property   'toString' of undefined
enet.0 | 2021-01-07 11:00:34.372 | error | (4482) uncaught exception: Cannot read property   'toString' of undefined
enet.0 | 2021-01-07   11:00:34.311 | debug | (4482) Starting Login   into eNet Server
enet.0 | 2021-01-07 11:00:34.310 | info | (4482) Running eNet Adapter Version 1.0.1,   Configured eNet Server: 192.168.153.110, Username: iobroker
enet.0 | 2021-01-07 11:00:34.284 | info | (4482) starting. Version 1.0.1 in /opt/iobroker/node_modules/iobroker.enet,   node: v12.20.0, js-controller: 3.1.6
enet.0 | 2021-01-07   11:00:34.186 | debug | (4482) statesDB   connected
enet.0 | 2021-01-07   11:00:34.185 | debug | (4482) States   connected to redis: 127.0.0.1:9000
enet.0 | 2021-01-07   11:00:34.178 | debug | (4482) States create   System PubSub Client
enet.0 | 2021-01-07   11:00:34.175 | debug | (4482) States create   User PubSub Client
enet.0 | 2021-01-07   11:00:34.170 | debug | (4482) Redis States:   Use Redis connection: 127.0.0.1:9000
enet.0 | 2021-01-07   11:00:34.167 | debug | (4482) objectDB   connected
enet.0 | 2021-01-07   11:00:34.161 | debug | (4482) Objects   connected to redis: 127.0.0.1:9001
enet.0 | 2021-01-07   11:00:34.149 | debug | (4482) Objects client   initialize lua scripts
enet.0 | 2021-01-07   11:00:34.148 | debug | (4482) Objects create   User PubSub Client
enet.0 | 2021-01-07   11:00:34.147 | debug | (4482) Objects create   System PubSub Client
enet.0 | 2021-01-07   11:00:34.143 | debug | (4482) Objects client   ready ... initialize now
enet.0 | 2021-01-07   11:00:34.112 | debug | (4482) Redis Objects:   Use Redis connection: 127.0.0.1:9001
host.raspberrypi | 2021-01-07 11:00:33.230 | info | instance system.adapter.enet.0 started with   pid 4482

Unter Objekte findet sich nur:
![image](https://user-images.githubusercontent.com/70587675/103884675-31e5b980-50df-11eb-9136-6a1ab690013e.png)

Instanzen:
![image](https://user-images.githubusercontent.com/70587675/103887521-75422700-50e3-11eb-91ab-416af72ef176.png)

Grüße
Franz

**Comment by stoffel7** [comment]
ist es möglich Zugriff auf den Server zu bekommen, da scheint wider was am Login geändert worden zu sein...

**Comment by FranzKillig** [comment]
@stoffel7 wäre kein Problem, auf welche weise? Per Teamviewer über meine Rechner oder soll ich einen Benutzer mit externem Zugriff anlegen?

**Comment by FranzKillig** [comment]
Benutzer mit externem Zugriff  geht ja gar nicht, dafür müsste das Gerät ja in meinem Netzwerk sein.

**Comment by stoffel7** [comment]
externer Zugriff ( Portfreigabe auf den Server) wäre schon sinnvoll, für Teamviewer muss der Server ja auch am Netz sein…
läuft der Server schon produktiv?



Von: Franz Killig <notifications@github.com>
Gesendet: Donnerstag, 7. Januar 2021 14:57
An: SebastianSchultz/ioBroker.enet
Cc: stoffel7; Mention
Betreff: Re: [SebastianSchultz/ioBroker.enet] Keine Kommunikation mit eNet-Server Version 2.3.0 (#29)





** CAUTION - email originated from outside the Schaeffler organization






Benutzer mit externem Zugriff geht ja gar nicht, dafür müsste das Gerät ja in meinem Netzwerk sein.

**Comment by FranzKillig** [comment]
Kurz zum Verständnis; Mit Server meinst du den eNet-Server oder den Raspi?

Über den eNet-Server läuft meine gesamte Rollladen- und Verschattungsanlage als auch die gesamte Außenbeleuchtung nebst Sprinkleranlage für den Rasen.  Der ist also "produktiv"
Auf dem Raspi läuft derzeit nur ioBroker mit einem unwichtigen Skript. Also "nicht produktiv"

Was benötigst du also? Für welchen Server soll ich dir welche Ports öffnen und einen User anlegen.
Ich würde dir dann die Zugangsdaten mit meiner statischen IP per PN zusenden.

**Comment by stoffel7** [comment]
ich brauche eigentlich nur den Zugriff auf den eNet-Server… (von aussen).
zum testen wegen login, kann es sein dass ich den dann mal neu booten muß dann ist halt kurzfristig kein Zugriff auf deine Steuerung möglich…
bin sowieso mal gespannt… ich simulier mit dem Adapter eigentlich eine Installation…



Von: Franz Killig <notifications@github.com>
Gesendet: Donnerstag, 7. Januar 2021 15:46
An: SebastianSchultz/ioBroker.enet
Cc: stoffel7; Mention
Betreff: Re: [SebastianSchultz/ioBroker.enet] Keine Kommunikation mit eNet-Server Version 2.3.0 (#29)





** CAUTION - email originated from outside the Schaeffler organization






Kurz zum Verständnis; Mit Server meinst du den eNet-Server oder den Raspi?

Über den eNet-Server läuft meine gesamte Rollladen- und Verschattungsanlage als auch die gesamte Außenbeleuchtung nebst Sprinkleranlage für den Rasen. Der ist also "produktiv"
Auf dem Raspi läuft derzeit nur ioBroker mit einem unwichtigen Skript. Also "nicht produktiv"

Was benötigst du also? Für welchen Server soll ich dir welche Ports öffnen und einen User anlegen.
Ich würde dir dann die Zugangsdaten mit meiner statischen IP per PN zusenden.

**Comment by FranzKillig** [comment]
@stoffel7 
Da es hier wohl keine Möglichkeit mehr einer PN gibt, habe ich Basti eben die Zugangsdaten per Mail gesendet in der Hoffnung, dass er diese an dich weiterleiten kann.

**Comment by FrrankL** [comment]
Guten Morgen,

ich habe selbiges Problem mit der V2.3.0 auf dem Gira Server. Wenn man hier noch irgendwie helfen kann.

**Comment by SebastianSchultz** [comment]
Wann hast Du den Adapter und wie installiert?
Momentan ist alles noch im Alpha Status, wir arbeiten aber dran.

**Comment by FrrankL** [comment]
Hi, ich bin erst seid gut 2 Wochen dabei. Ich habe den Adapter zunächst über ioBroker installiert, habe dann aber den "ical" Fehler bekommen wie im Thread "Fehlermeldungen beim Einschalten des Adapters #22".
Nach Installation über Github war er dann aber weg und dann habe ich diesen Thread hier gesehen.
Grüße

**Comment by oschmidteu** [comment]
Wollte nur mal meinen Input da lassen.
Bin noch absoluter ioBroker Anfänger aber habe den Adapter in der Version 1.0.2.  installiert und konnte meinen eNet Server (2.3.0) hinzufügen bzw. 

Ich kann auch sehen das alle Objekte angelegt sind jedoch kann ich damit bisher noch nichts anfangen da ich mich mit ioBroker noch nicht genug auseinandergesetzt habe.

**Comment by stoffel7** [comment]
welchen Art von Devices wurden denn angelegt?
Rollladen, Schalter???
es sollten zu jedem Device die entsprechenden INPUT und OUTPUT Objekte angelegt sein…
wenn man da Werte ändert( Bsp: für Rollladen „Current Absolut Position…“  oder Licht Dimmen „Actual Dimming value..“ dann sollte sich auch was ändern 😉



Von: oschmidteu ***@***.***>
Gesendet: Mittwoch, 14. April 2021 11:33
An: SebastianSchultz/ioBroker.enet
Cc: Stefan Bruder; Mention
Betreff: Re: [SebastianSchultz/ioBroker.enet] Keine Kommunikation mit eNet-Server Version 2.3.0 (#29)





** CAUTION - email originated from outside the Schaeffler organization






Wollte nur mal meinen Input da lassen.
Bin noch absoluter ioBroker Anfänger aber habe den Adapter in der Version 1.0.2. installiert und konnte meinen eNet Server (2.3.0) hinzufügen bzw.

Ich kann auch sehen das alle Objekte angelegt sind jedoch kann ich damit bisher noch nichts anfangen da ich mich mit ioBroker noch nicht genug auseinandergesetzt habe.

**Comment by oschmidteu** [comment]
Ist alles vorhanden:
![image](https://user-images.githubusercontent.com/13415307/114691575-1c081600-9d18-11eb-9be4-6bab1027238a.png)

Ich wollte nur sagen, dass ich aktuell damit noch nicht arbeiten kann, da ich nicht weiß wie ;)

Aktuell sind (Licht)schalter und Dimm/Schaltaktoren eingebunden ggf. kommt bei zeiten noch ein Präsenzmelder dazu.

**Comment by stoffel7** [comment]
also dann schalt halt mal das Licht an ( Wet >0)

![grafik](https://user-images.githubusercontent.com/39948331/114695463-f11fc100-9d1b-11eb-992a-d3ba816344db.png)

**Comment by ringel17** [comment]
Hallo zusammen, ich kann mich leider noch nicht einloggen. Es scheitert anscheinend am SSL. Ich könnte beim Testen grundsätzlich unterstützen. 

VG
Jörg

host.raspberrypi | 2021-04-15 15:14:46.098 | info | Do not restart adapter system.adapter.enet.0 because disabled or deleted
-- | -- | -- | --
host.raspberrypi | 2021-04-15 15:14:46.097 | error | instance system.adapter.enet.0 terminated with code 3 (NO_ADAPTER_CONFIG_FOUND)
enet.0 | 2021-04-15 15:14:45.579 | warn | (28499) Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason
enet.0 | 2021-04-15 15:14:45.491 | error | (28499) adapter disabled
host.raspberrypi | 2021-04-15 15:14:28.756 | info | "system.adapter.enet.0" disabled
host.raspberrypi | 2021-04-15 15:14:13.654 | info | Restart adapter system.adapter.enet.0 because enabled
host.raspberrypi | 2021-04-15 15:14:13.654 | info | instance system.adapter.enet.0 terminated with code 0 (NO_ERROR)
enet.0 | 2021-04-15 15:14:13.181 | error | at WriteWrap.afterWrite [as oncomplete] (net.js:789:14)
enet.0 | 2021-04-15 15:14:13.181 | error | (28454) Error: write EPROTO 3069557200:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
enet.0 | 2021-04-15 15:14:13.180 | error | (28454) uncaught exception: write EPROTO 3069557200:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
enet.0 | 2021-04-15 15:14:13.137 | info | (28454) Terminated (NO_ERROR): Without reason
enet.0 | 2021-04-15 15:14:13.136 | info | (28454) terminating
enet.0 | 2021-04-15 15:14:13.133 | info | (28454) eNet Server Logout, Tschuess ....
enet.0 | 2021-04-15 15:14:13.120 | error | at WriteWrap.afterWrite [as oncomplete] (net.js:789:14)
enet.0 | 2021-04-15 15:14:13.120 | error | (28454) Error: write EPROTO 3069557200:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
enet.0 | 2021-04-15 15:14:13.119 | error | (28454) uncaught exception: write EPROTO 3069557200:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
enet.0 | 2021-04-15 15:14:12.980 | info | (28454) Starting Login into eNet Server
enet.0 | 2021-04-15 15:14:12.976 | info | (28454) Running eNet Adapter Version 1.0.2, Configured eNet Server: 192.168.0.213 (SSL/HTTPS), Username: admin on port 80
enet.0 | 2021-04-15 15:14:12.933 | info | (28454) starting. Version 1.0.2 in /opt/iobroker/node_modules/iobroker.enet, node: v10.19.0, js-controller: 3.1.6
host.raspberrypi | 2021-04-15 15:14:11.125 | info | instance system.adapter.enet.0 started with pid 28454
host.raspberrypi | 2021-04-15 15:14:11.077 | info | "system.adapter.enet.0" enabled

**Comment by stoffel7** [comment]
bitte im Adapter-Config Port 443 einstellen…

Von: ringel17 ***@***.***>
Gesendet: Donnerstag, 15. April 2021 15:19
An: SebastianSchultz/ioBroker.enet
Cc: Stefan Bruder; Mention
Betreff: Re: [SebastianSchultz/ioBroker.enet] Keine Kommunikation mit eNet-Server Version 2.3.0 (#29)





** CAUTION - email originated from outside the Schaeffler organization






Hallo zusammen, ich kann mich leider noch nicht einloggen. Es scheitert anscheinend am SSL. Ich könnte beim Testen grundsätzlich unterstützen.

VG
Jörg
host.raspberrypi
2021-04-15 15:14:46.098
info
Do not restart adapter system.adapter.enet.0 because disabled or deleted
host.raspberrypi
2021-04-15 15:14:46.097
error
instance system.adapter.enet.0 terminated with code 3 (NO_ADAPTER_CONFIG_FOUND)
enet.0
2021-04-15 15:14:45.579
warn
(28499) Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason
enet.0
2021-04-15 15:14:45.491
error
(28499) adapter disabled
host.raspberrypi
2021-04-15 15:14:28.756
info
"system.adapter.enet.0" disabled
host.raspberrypi
2021-04-15 15:14:13.654
info
Restart adapter system.adapter.enet.0 because enabled
host.raspberrypi
2021-04-15 15:14:13.654
info
instance system.adapter.enet.0 terminated with code 0 (NO_ERROR)
enet.0
2021-04-15 15:14:13.181
error
at WriteWrap.afterWrite [as oncomplete] (net.js:789:14)
enet.0
2021-04-15 15:14:13.181
error
(28454) Error: write EPROTO 3069557200:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
enet.0
2021-04-15 15:14:13.180
error
(28454) uncaught exception: write EPROTO 3069557200:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
enet.0
2021-04-15 15:14:13.137
info
(28454) Terminated (NO_ERROR): Without reason
enet.0
2021-04-15 15:14:13.136
info
(28454) terminating
enet.0
2021-04-15 15:14:13.133
info
(28454) eNet Server Logout, Tschuess ....
enet.0
2021-04-15 15:14:13.120
error
at WriteWrap.afterWrite [as oncomplete] (net.js:789:14)
enet.0
2021-04-15 15:14:13.120
error
(28454) Error: write EPROTO 3069557200:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
enet.0
2021-04-15 15:14:13.119
error
(28454) uncaught exception: write EPROTO 3069557200:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
enet.0
2021-04-15 15:14:12.980
info
(28454) Starting Login into eNet Server
enet.0
2021-04-15 15:14:12.976
info
(28454) Running eNet Adapter Version 1.0.2, Configured eNet Server: 192.168.0.213 (SSL/HTTPS), Username: admin on port 80
enet.0
2021-04-15 15:14:12.933
info
(28454) starting. Version 1.0.2 in /opt/iobroker/node_modules/iobroker.enet, node: v10.19.0, js-controller: 3.1.6
host.raspberrypi
2021-04-15 15:14:11.125
info
instance system.adapter.enet.0 started with pid 28454
host.raspberrypi
2021-04-15 15:14:11.077
info
"system.adapter.enet.0" enabled

**Comment by SebastianSchultz** [comment]
Gibts es hierzu eine Rückmeldung?

**Comment by stoffel7** [comment]
Mit der aktuellen Adapter-Version müßte es mit allen eNet-Server Versionen gehen.

Von meinem iPad gesendet

**Comment by SebastianSchultz** [comment]
@ringel17 Funktioniert es mit der aktuellen Version? Falls ja, dann bitte das Issue hier schließen.

**Comment by FranzKillig** [comment]
@ringel17 Beim Login geduldig sein. Bei mir (aktuellste Serverversion) benötigt es ab und an auch mal 3-4 Versuche bis es klappt.

**Comment by ringel17** [comment]
Hallo zusammen,

der Login klappt. Es werden aber keine Inhalte geladen, sondern nur die Objekte des Info-Bereiches. Bei manchen Starts wird der Adapter aber auch terminiert. 

@Franz Nach ein paar automatischen Restart erkennt iobroker eine Loop und bricht die Restart ab.

Vielleicht stelle ich mich zu dumm an, um die Version 1.0.52 zu laden. Auch bei Verwendung des Links erhalte ich die Version 1.0.2.

VG
Jörg

host.raspberrypi | 2021-05-07 08:14:29.642 | info | Restart adapter system.adapter.enet.1 because enabled
-- | -- | -- | --
host.raspberrypi | 2021-05-07 08:14:29.637 | error | instance system.adapter.enet.1 terminated with code 6 (UNCAUGHT_EXCEPTION)
enet.1 | 2021-05-07 08:14:29.190 | info | (7386) State value to set for "enet.1.info.CounterID" has to be type "string" but received type "number"
enet.1 | 2021-05-07 08:14:29.097 | info | (7386) State value to set for "enet.1.info.CounterID" has to be type "string" but received type "number"
enet.1 | 2021-05-07 08:14:29.088 | info | (7386) eNet Server Logout, Tschuess ....
enet.1 | 2021-05-07 08:14:29.074 | warn | (7386) Terminated (UNCAUGHT_EXCEPTION): Without reason
enet.1 | 2021-05-07 08:14:29.071 | info | (7386) terminating
enet.1 | 2021-05-07 08:14:29.058 | error | (7386) Cannot read property 'deviceUIDs' of undefined
enet.1 | 2021-05-07 08:14:29.057 | error | (7386) TypeError: Cannot read property 'deviceUIDs' of undefined at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.enet/main.js:1:40697) at IncomingMessage.emit (events.js:32
enet.1 | 2021-05-07 08:14:29.052 | error | (7386) uncaught exception: Cannot read property 'deviceUIDs' of undefined
enet.1 | 2021-05-07 08:14:17.523 | info | (7386) State value to set for "enet.1.info.CounterID" has to be type "string" but received type "number"
enet.1 | 2021-05-07 08:14:17.483 | info | (7386) State value to set for "enet.1.info.CounterID" has to be type "string" but received type "number"
enet.1 | 2021-05-07 08:14:17.482 | info | (7386) State value to set for "enet.1.info.CounterID" has to be type "string" but received type "number"
enet.1 | 2021-05-07 08:14:17.481 | info | (7386) State value to set for "enet.1.info.CounterID" has to be type "string" but received type "number"
enet.1 | 2021-05-07 08:14:17.480 | info | (7386) State value to set for "enet.1.info.CounterID" has to be type "string" but received type "number"
enet.1 | 2021-05-07 08:14:17.475 | info | (7386) State value to set for "enet.1.info.CounterID" has to be type "string" but received type "number"
enet.1 | 2021-05-07 08:14:17.449 | warn | (7386) State "enet.1.info.requestEvents" has no existing object, this might lead to an error in future versions
enet.1 | 2021-05-07 08:14:17.448 | info | (7386) State value to set for "enet.1.info.CounterID" has to be type "string" but received type "number"
enet.1 | 2021-05-07 08:14:05.387 | info | (7386) Starting Login into eNet Server
enet.1 | 2021-05-07 08:14:05.384 | info | (7386) Running eNet Adapter Version 1.0.2, Configured eNet Server: 192.168.0.213 (SSL/HTTPS), Username: benutzer on port 443
enet.1 | 2021-05-07 08:14:05.355 | info | (7386) starting. Version 1.0.2 in /opt/iobroker/node_modules/iobroker.enet, node: v12.22.1, js-controller: 3.3.8

**Comment by stoffel7** [comment]
das sieht nicht danach aus, als würde der LOGIN wirklich klappen, stimmt denn HTTPS mit port 443?
schick mir mal 'ne PM

**Comment by ringel17** [comment]
Ich kann hier keine Möglichkeit für eine PM finden.

Adresse und Port sind korrekt. Ich habe andere Kombinationen versucht. Dann kommen Info zum fehlerhaften Login.

**Comment by stoffel7** [comment]
brudst<at>yahoo<dot>de

Von meinem iPad gesendet

**Comment by stoffel7** [comment]
Problem lag auf eNet-Server Seite (lt. ringel17) kann geschlossen werden...
